### ISSUE TITLE
Site logo

### ISSUE THREAD

**Issue by KrijnHoetmer** [Tristandemuijnck/all-human-accessible-website#1]
Kan dit lekkerder? :)

https://github.com/Tristandemuijnck/all-human-accessible-website/blob/803011c993d38e56743dc0ca2a59655b84efc554/index.html#L17

**Comment by Tristandemuijnck** [comment]
5a41b0d600e6822446b8b0e3958b4f77ac3c0bfb

Veranderd naar Logo Vervoerregio Amsterdam
